# Spring配置
spring:
  datasource:
    # 驱动类名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接的url
    url: jdbc:mysql://localhost:3306/tlias
    # 连接数据库的用户名
    username: root
    # 连接数据库的密码
    password: 123456

  servlet:
    multipart:
      # 配置单个文件最大上传大小
      max-file-size: 10MB
      # 配置单个请求最大上传大小(一次请求可以上传多个文件)
      max-request-size: 100MB

# MyBatis配置
mybatis:
  configuration:
    # 开启mybatis的日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启数据库表字段 到 实体类属性的驼峰映射
    map-underscore-to-camel-case: true

#阿里云配置
aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5tLWDHehrbNiP8ju91n4
    accessKeySecret: 0JBpHsQz3kzmqlWbkZRUBzZS6vRF3V
    securityToken: CAISnwJ1q6Ft5B2yfSjIr5b4fN/51aZSwpKSdnHcsFFjVeZdt6H41jz2IHtOfHBgAOsZsf41lWBZ7/oalqJ9RplKVEvZdNZ56MzSOd4lntOT1fau5Jko1be0ewHKeQKZsebWZ+LmNpy/Ht6md1HDkAJq3LL+bk/Mdle5MJqP+/kFC9MMRVuAcCZhDtVbLRcYgq18D3bKMuu3ORPHm3fZCFES2jBxkmRi86+ysIP+phPVlw/90fRH5dazcJapacZ9O4pmTt6zm8Fmf6/Z1CN86gINtoUO1fcdpGuX4Y7NWgIBskzWbdC5qIM/cFVLAYEhALNBofTGkvl1h/fejYyfyWwWZrsNCnSGH9//mpGVSLLwao4jG6zyPnPWycBl2VtyBubnCxqAAVlZVBAYNdtqmuZ7jZxCJeOnOHIHuGa64xKGMl3QjhCGERvVo3UHsnzlJ0uFa4Fx/0r+YL/Jn87vwLcxXtm6BG2LLK8FZZabLYtwIaJnSYEr9nnLdKblDZmQEbU1gfFIv57cMMndtxkmgY0nLQWiSisZyOvNHD3QFqFJesmZvxVE
    bucketName: fengyouquan

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug